### ISSUE TITLE
question about "gen_pose_cond = True"

### ISSUE THREAD

**Issue by stime111** [VivianSZF/pof3d#1]
Thanks for your outstanding work.However, as I read through the code, I find that the "gen_pose_cond = True" seems to use the ground truth camera pose as mapping network condition.Is that necessary for image generation?

**Comment by VivianSZF** [comment]
Hi, we do not use the ground truth camera poses for training. Please check the implementation of mapping network at https://github.com/VivianSZF/pof3d/blob/main/training/networks_stylegan2.py#L280.

**Comment by stime111** [comment]
> Hi, we do not use the ground truth camera poses for training. Please check the implementation of mapping network at https://github.com/VivianSZF/pof3d/blob/main/training/networks_stylegan2.py#L280.

Thanks for your explaination.

**Comment by stime111** [comment]
I'm quite sorry to reopen this question since i find i just mistake the "MappingNetwork" and "MappingNetworkPose". 
thanks for your explaination and great work again.
